# Generated by Django 5.0.2 on 2024-02-29 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
                ('point', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(blank=True, max_length=200, null=True)),
                ('option2', models.CharField(blank=True, max_length=200, null=True)),
                ('option3', models.CharField(blank=True, max_length=200, null=True)),
                ('option4', models.CharField(blank=True, max_length=200, null=True)),
                ('time_limit', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Question.quizcategory')),
            ],
            options={
                'verbose_name_plural': 'QuestionModel',
            },
        ),
        migrations.CreateModel(
            name='Performace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_que', models.PositiveIntegerField()),
                ('attempt_que', models.PositiveIntegerField()),
                ('points', models.PositiveBigIntegerField()),
                ('true_que', models.PositiveIntegerField()),
                ('wrong_que', models.PositiveIntegerField()),
                ('result', models.BooleanField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quize_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Question.quizcategory', to_field='title')),
            ],
        ),
    ]
